all:
	g++ src/app.cpp src/general.cpp src/trip.cpp src/dijkstra.cpp src/graph.cpp src/logger.cpp src/main.cpp src/memory_utils.cpp src/route.cpp src/ui.cpp -std=c++17 -Wall -O3 -lncursesw -o graphs


